src/Entity/ShopOrder.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShopOrderRepository")
 */
class ShopOrder
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $order_id;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $shipping_status;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0, nullable=true)
     */
    private $shipping_price;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $shipping_payment_status;

    /**
     * @ORM\Column(type="string", length=16, nullable=true)
     */
    private $payment_status;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ShopOrderProduct", mappedBy="shop_order")
     */
    private $shop_order_products;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    public function __construct()
    {
        $this->shop_order_products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderId(): ?string
    {
        return $this->order_id;
    }

    public function setOrderId(string $order_id): self
    {
        $this->order_id = $order_id;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getShippingStatus(): ?string
    {
        return $this->shipping_status;
    }

    public function setShippingStatus(string $shipping_status): self
    {
        $this->shipping_status = $shipping_status;

        return $this;
    }

    public function getShippingPrice(): ?string
    {
        return $this->shipping_price;
    }

    public function setShippingPrice(?string $shipping_price): self
    {
        $this->shipping_price = $shipping_price;

        return $this;
    }

    public function getShippingPaymentStatus(): ?string
    {
        return $this->shipping_payment_status;
    }

    public function setShippingPaymentStatus(?string $shipping_payment_status): self
    {
        $this->shipping_payment_status = $shipping_payment_status;

        return $this;
    }

    public function getPaymentStatus(): ?string
    {
        return $this->payment_status;
    }

    public function setPaymentStatus(?string $payment_status): self
    {
        $this->payment_status = $payment_status;

        return $this;
    }

    public function getShopOrderProducts(): Collection
    {
        return $this->shop_order_products;
    }

    public function setShopOrderProduct(ShopOrderProduct $model): self
    {
        if (!$this->shop_order_products->contains($model)) {
            $this->shop_order_products[] = $model;
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/ShopOrderProduct.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ShopOrderProductRepository")
 */
class ShopOrderProduct
{
    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\ShopOrder", inversedBy="shop_order_products")
     * @ORM\JoinColumn(name="shop_order_id", referencedColumnName="id", nullable=false)
     */
    protected $shop_order;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="shop_order_products")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id", nullable=false)
     */
    protected $product;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $cost;

    /**
     * @ORM\Column(type="smallint")
     */
    private $tax_perc;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $tax_amt;

    /**
     * @ORM\Column(type="smallint")
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tracking_number;

    /**
     * @ORM\Column(type="string", length=1)
     */
    private $canceled;

    /**
     * @ORM\Column(type="string", length=16)
     */
    private $shipped_status_sku;

    public function getShopOrder(): ?ShopOrder
    {
        return $this->shop_order;
    }

    public function setShopOrder(?ShopOrder $shop_order): self
    {
        $this->shop_order = $shop_order;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getCost(): ?string
    {
        return $this->cost;
    }

    public function setCost(string $cost): self
    {
        $this->cost = $cost;

        return $this;
    }

    public function getTaxPerc(): ?int
    {
        return $this->tax_perc;
    }

    public function setTaxPerc(int $tax_perc): self
    {
        $this->tax_perc = $tax_perc;

        return $this;
    }

    public function getTaxAmt(): ?string
    {
        return $this->tax_amt;
    }

    public function setTaxAmt(string $tax_amt): self
    {
        $this->tax_amt = $tax_amt;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTrackingNumber(): ?string
    {
        return $this->tracking_number;
    }

    public function setTrackingNumber(string $tracking_number): self
    {
        $this->tracking_number = $tracking_number;

        return $this;
    }

    public function getCanceled(): ?string
    {
        return $this->canceled;
    }

    public function setCanceled(string $canceled): self
    {
        $this->canceled = $canceled;

        return $this;
    }

    public function getShippedStatusSku(): ?string
    {
        return $this->shipped_status_sku;
    }

    public function setShippedStatusSku(string $shipped_status_sku): self
    {
        $this->shipped_status_sku = $shipped_status_sku;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\ShopOrder;
use App\Repository\ShopOrderRepository;
use App\Service\OrderStorage;
use App\Service\OrderSynchronizerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    private $logger;
    private $order_storage;

    public function __construct(LoggerInterface $logger, OrderStorage $order_storage)
    {
        $this->logger = $logger;
        $this->order_storage = $order_storage;
    }

    /**
     * @Route("/", name="home")
     */
    public function index(
        OrderSynchronizerInterface $synchronizer,
        ShopOrderRepository $repository
    )
    {
        $list = $synchronizer->getOrderList(20, date('Y-m-d'), date('Y-m-d'));

        if (!empty($list)) {
            $this->order_storage->store($list);
        }

        $current_date = new \DateTimeImmutable();
        $order_list = $repository->findByDate($current_date);

        return $this->render('home/index.html.twig', [
            'current_date' => $current_date->format('d.m.Y'),
            'order_list' => $order_list
        ]);
    }

    /**
     * @Route("/order/{id}", name="order")
     */
    public function order(ShopOrder $order)
    {
        // here we can call __getOrder__ method from OrderSynchronizerInterface, but we already have all information in local DB from __orders_search__ API method
        return $this->render('home/order.html.twig', [
            'order' => $order
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order list{% endblock %}

{% block body %}

    <h1 class="text-center py-3">Orders list {{ current_date }}</h1>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Order #</th>
                <th>ID</th>
                <th>Phone</th>
                <th>Shipping status</th>
                <th>Shipping price</th>
                <th>Shipping payment status</th>
                <th>Payment status</th>
            </tr>
        </thead>
        <tbody>
        {% for order in order_list %}
            <tr>
                <td>{{ loop.index }}</td>
                <td><a href="{{ path('order', {'id': order.id}) }}">{{ order.orderId }}</a></td>
                <td>{{ order.phone }}</td>
                <td>{{ order.shippingStatus }}</td>
                <td>{{ order.shippingPrice }}</td>
                <td>{{ order.shippingPaymentStatus }}</td>
                <td>{{ order.paymentStatus }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/home/order.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order info{% endblock %}

{% block body %}

    <h1 class="text-center py-3">Order #{{ order.orderId }} info</h1>

    <table class="table table-bordered table-hover">
        <tbody>
        <tr>
            <td>Order #</td>
            <td>{{ order.id }}</td>
        </tr>
        <tr>
            <td>ID</td>
            <td>{{ order.orderId }}</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>{{ order.phone }}</td>
        </tr>
        <tr>
            <td>Shipping status</td>
            <td>{{ order.shippingStatus }}</td>
        </tr>
        <tr>
            <td>Shipping price</td>
            <td>{{ order.shippingPrice }}</td>
        </tr>
        <tr>
            <td>Shipping payment status</td>
            <td>{{ order.shippingPaymentStatus }}</td>
        </tr>
        <tr>
            <td>Payment status</td>
            <td>{{ order.paymentStatus }}</td>
        </tr>
        </tbody>
    </table>

    <h2 class="text-center py-1">Ordered product list</h2>

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <td>#</td>
                <td>barcode</td>
                <td>price</td>
                <td>Cost</td>
                <td>Tax percent</td>
                <td>Tax amount</td>
                <td>Quantity</td>
                <td>Tracking number</td>
                <td>Cancelled</td>
                <td>Shipped status sku</td>
            </tr>
        </thead>
        <tbody>
        {% for op in order.getShopOrderProducts() %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ op.product.barcode }}</td>
                <td>{{ op.product.price }}</td>
                <td>{{ op.cost }}</td>
                <td>{{ op.taxPerc }}</td>
                <td>{{ op.taxAmt }}</td>
                <td>{{ op.quantity }}</td>
                <td>{{ op.trackingNumber }}</td>
                <td>{{ op.canceled }}</td>
                <td>{{ op.shippedStatusSku }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <div class="text-center">
        <a href="{{ url('home') }}" class="btn btn-primary btn-lg">Back</a>
    </div>

{% endblock %}